version: '3.9'

networks:
  application:

services:
  server:
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    container_name: server
    build:
      context: ./
      dockerfile:  ./build/Dockerfile
    environment:
      POSTGRES_PASSWORD: very_difficult_postgress_password
      POSTGRES_USER: service_user
      POSTGRES_DB:  service_db
      POSTGRES_HOST: postgresdb
      POSTGRES_PORT: 5432
    ports:
      - "80:80"
    command: "gunicorn   --bind 0.0.0.0:80 service.wsgi"
    networks:
          - application

  db:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_PASSWORD: very_difficult_postgress_password
      POSTGRES_USER: service_user
      POSTGRES_DB: service_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U service_user -d service_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./. Init Database:/docker-entrypoint-initdb.d
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
          - application

  adminer:
    image: adminer
    container_name: postgres-adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
          - application
    