# Generated by Django 4.1.7 on 2023-03-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('metadata', models.JSONField(default=None, null=True)),
                ('parents_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ParentChannelRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_parents', to='film_api.channel')),
                ('parentFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_subchannels', to='film_api.channel')),
            ],
        ),
        migrations.CreateModel(
            name='ContentRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_channels', to='film_api.content')),
                ('parentFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_contents', to='film_api.channel')),
            ],
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('fileType', models.CharField(choices=[('VI', 'Video file'), ('PF', 'PDF file'), ('TX', 'Text file')], default='VI', max_length=2)),
                ('contentFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_api.content')),
            ],
        ),
        migrations.AddConstraint(
            model_name='parentchannelrel',
            constraint=models.UniqueConstraint(fields=('channelFK', 'parentFK'), name='unique_channel_rel'),
        ),
        migrations.AddConstraint(
            model_name='contentrel',
            constraint=models.UniqueConstraint(fields=('contentFK', 'parentFK'), name='unique_content_rel'),
        ),
    ]
