# Generated by Django 4.1.7 on 2023-03-06 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('parents_count', models.IntegerField(default=0)),
                ('content_count', models.IntegerField(default=0)),
                ('subchannels_count', models.IntegerField(default=0)),
                ('parentChannels', models.ManyToManyField(blank=True, default=None, related_name='child_channels', to='film_api.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('metadata', models.JSONField(blank=True, default=None, null=True)),
                ('parentChannels', models.ManyToManyField(default=None, related_name='child_contents', to='film_api.channel')),
            ],
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('fileType', models.CharField(choices=[('VI', 'Video file'), ('PF', 'PDF file'), ('TX', 'Text file')], default='VI', max_length=2)),
                ('contentFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='film_api.content')),
            ],
        ),
    ]
